### ISSUE TITLE
SteamVr 2.2 Teleport bug

### ISSUE THREAD

**Issue by Warsoul112** [ValveSoftware/steamvr_unity_plugin#429] opened 2019-05-16 05:20 UTC
https://www.twitch.tv/videos/425487873

I need help with steamvr 2.2 on unity 2018.4. I use an Teleport Area component to teleport on a basic plane but i can only teleport into one of the four quadrant on the plane (X+,Z+) Other quadrant block the teleporter but i can spam the teleport to force a teleportation. Teleport Point work only on (X+,Z+) quadrant. Others quadrants block the Teleport Point.

**Comment by zite** [comment] 2019-05-24 18:21
It looks like you're missing a collider for that section of your teleport area. Maybe try a cube instead of a plane just to be sure?

**Comment by Warsoul112** [comment] 2019-05-24 19:45
Nop, the teleport work only on x+ and z+. I have to slide my level fully into that quadrant or the teleport won't work on other quadrant.

**Comment by zite** [comment] 2019-05-27 21:52
I just made the longbow teleport area 1x1 (plane) and moved it to 0, 0.5, 0, and was able to teleport into all quadrants of it. Is your plane possibly rotated on an axis so it's dipping below your floor?

**Comment by zite** [comment] 2019-05-27 21:55
In that video there's some errors happening, maybe they're the cause?

**Comment by zite** [comment] 2019-06-07 18:17
I'm going to close this issue for now. If you are still having this issue let me know and please provide an example project as I'm not able to replicate this bug locally.

**Comment by Warsoul112** [comment] 2019-06-07 21:28
Yeah, i still have this issue.

I solved the problem by offseting my Stage completly into the x+,z+ quadrant.
I can upload an empty project with steam vr 2.2 and unity 2018.3

**Comment by Warsoul112** [comment] 2019-06-07 23:50
A ripped, almost empty version to showcase the bug :  https://www.mediafire.com/file/qmdz8fe7q38c2xb/VR-Z.zip/file

**Comment by Warsoul112** [comment] 2019-06-10 06:08
You can reproduce the issue ?

**Comment by zite** [comment] 2019-06-14 00:06
I can reproduce the issue with your project but have no idea why. I am not able to reproduce this with my own project.

**Comment by Warsoul112** [comment] 2019-06-14 06:44
Yeah, it always happen to me. How i can fix this ? Starting a new project ?

**Comment by zite** [comment] 2021-04-28 21:04
Pretty sure this has been fixed. If not please create a new issue with repro steps and ideally an example project. Thanks!

**Closed by zite** 2021-04-28 21:04 UTC
Labels: Needs more information
