### ISSUE TITLE
Strange tearing with latest SteamVR and/or SDK

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#254] opened 2019-01-03 23:25 UTC
I have observed a strange tearing effect I'm not sure but I dont think it syncs between the two eyes either. It does not happen all the time but sporadically. Cant tell if its 2.2b3 or SteamVR beta. Though it does happen on our stable branch too which uses 1.x SDK. I will revert to none SteamVR beta and see if it happen there too

**Comment by AndersMalmgren** [comment] 2019-01-03 23:35
It was present with stable branch SteamVR too. Only other thing I can think of is that I recently upgraded Nvidia GPU drivers to 417,35

**Comment by AndersMalmgren** [comment] 2019-01-31 07:14
Yes let me try later with latest version of GPU drivers and plugin etc and see if it still remains.

**Comment by AndersMalmgren** [comment] 2019-01-31 11:57
Okey, I ran DDU and then reinstaled GPU drivers. My current setup.

Nvidia 1080 TI with driver 417.71
SteamVR plugin 2.2.0 
SteamVR Beta Build 3513907
Unity 2017.4.19

The tearing remains

**Comment by zite** [comment] 2019-01-31 23:38
Is this with all SteamVR applications? Just in your unity editor? Just in a build?

**Comment by AndersMalmgren** [comment] 2019-02-01 07:30
It's in both built and editor but would say it's more in edtior.

**Comment by AndersMalmgren** [comment] 2019-02-02 13:02
@keithbradner Intersting enough the tearing does not show in OBS with teh OpenVR plugin. It only shows directly in the headset

**Comment by zite** [comment] 2019-02-06 22:39
Are you seeing this in other SteamVR titles?

**Comment by AndersMalmgren** [comment] 2019-02-06 23:39
It seems to be easiest to spot from editor. Its also easiest to spot with canvases while a new scene is loading async. 

In built mode its really hard to spot it.

**Comment by zite** [comment] 2019-02-08 02:32
Sounds like it may be a motion smoothing issue? If you bring up the SteamVR Settings windows does it say anything about that in the lower left hand corner with the framerate and ms?

**Comment by AndersMalmgren** [comment] 2019-02-08 23:15
@keithbradner Its off, havent touch that btw

![image](https://user-images.githubusercontent.com/817577/52511326-c1d30e00-2bff-11e9-979f-3c2942ef912a.png)

**Comment by zite** [comment] 2019-02-09 00:25
Ah I meant to take a look at that while your project is running. It updates in realtime.

**Comment by AndersMalmgren** [comment] 2019-02-11 08:41
@keithbradner AH okey, will do tonight. Is motion smoothing a new feature?

**Comment by AndersMalmgren** [comment] 2019-02-12 23:28
@keithbradner 
Sorry for the slow response on this. Please check the video, the first spike is from nvidia shadowplay starting. Then when I click away the in game prompt canvas you see a spike. Here I get tearing. The tearing effect is something new that havent happened before.

https://www.youtube.com/watch?v=nYf5PwfB4lQ

**Comment by zite** [comment] 2019-02-19 04:57
Yeah I'm going to bet that's motion smoothing kicking in for a few frames. It's a feature to decrease framerate stuttering. My bet is unity GC or some editor process is causing that spike which then translates into SteamVR trying to smooth out the few frames around it. I believe this is by design but you can post to the OpenVR repo if you want more information / troubleshooting for it. I'm going to close this issue for now.

OpenVR repo: https://github.com/ValveSoftware/openvr

**Closed by zite** 2019-02-19 04:57 UTC
Labels: Need Retest

**Comment by AndersMalmgren** [comment] 2019-02-19 07:29
All right, it should be not reports of this if it's a intended behaviour, will check with them, thanks
