### ISSUE TITLE
Haptic for vive tracker has no response. Please Help!

### ISSUE THREAD

**Issue by dhjhero** [ValveSoftware/steamvr_unity_plugin#231] opened 2018-12-15 09:53 UTC
Could you please pay some attention to gigantic space vr game developers? How to get tracker haptic with hyperblaster back in steamVR new version? Also more than 12 trackers with pogo pin trigger input support please!

**Comment by kisak-valve** [comment] 2018-12-15 16:44
Closing as a duplicate of #230.

**Closed by kisak-valve** 2018-12-15 16:44 UTC
