### ISSUE TITLE
Broken haptic pulse with IL2CPP

### ISSUE THREAD

**Issue by m4ff** [ValveSoftware/steamvr_unity_plugin#98] opened 2018-07-20 22:35 UTC
In `openvr_api.cs` the method `TriggerHapticPulse(uint unControllerDeviceIndex, uint unAxisId, char usDurationMicroSec)` defines `usDurationMicroSec` as a `char`. In the signature of the native OpenVR method `usDurationMicroSec` is defined as an `unsigned short`, so the corresponding type in C# should be `ushort`.

This has never been a problem before with Mono builds, but it is now with Unity 2018 and IL2CPP for Windows Standalone. Running an IL2CPP build of my game, I noticed the haptic pulse was extremely weak. I'm guessing `usDurationMicroSec` is clamped down to a C++ `char`, which has a maximum value of 127.

I'm not sure if it's a bug in IL2CPP or if it's expected behaviour, but the fix is very easy: just make `usDurationMicroSec` a `ulong` in the signature of `TriggerHapticPulse` in `openvr_api.cs`. It will work perfectly both with Mono and IL2CPP.

**Comment by bddckr** [comment] 2018-07-21 06:22
See https://github.com/ValveSoftware/openvr/issues/472 from April 14th **2017**.

**Comment by kisak-valve** [comment] 2018-07-21 14:12
Closing as a duplicate of https://github.com/ValveSoftware/openvr/issues/472.

**Closed by kisak-valve** 2018-07-21 14:12 UTC
