### ISSUE TITLE
SteamVR disable Unity XR Input

### ISSUE THREAD

**Issue by Nicolasgaillard** [ValveSoftware/steamvr_unity_plugin#585] opened 2019-11-14 09:18 UTC
When I am using the steamVR asset and I use it in the scene, then when it will create new steamVR instance, the XR input (only button, position still works) from Unity will no more get data. In fact I can get the values but they are not updated.

The next snippet get the trigger input of the right controller and it works well without steamVR but when I will use it like the camera rig or anything else the input trigger value will always return the value that it had when steamVR init. Even worth the problem still persists after the suppression of the camera rig (or anything else calling steamVR assets). 

```        
var inputDevices = new List<UnityEngine.XR.InputDevice>();
UnityEngine.XR.InputDevices.GetDevices(inputDevices);

foreach (var device in inputDevices)
{
     if (device.role == InputDeviceRole.RightHanded)
      {
           Debug.LogWarning("Is trigger Working : " + device.TryGetFeatureValue(CommonUsages.triggerButton, out bool isTrigger) + " Trigger value ; " + isTrigger);
      }
}
```

I could easily reproduce this bug with a new blank project from UnityEditor 2019.2.* and the import of the steamVR assets.

**Comment by pandooux** [comment] 2019-11-14 15:41
So I found that it's a duplicate of #441
It is late now, @keithbradner do you think it will be working soon ? (months ? years ?)

**Comment by zite** [comment] 2019-11-22 01:06
Unfortunately the two systems are still not compatible with each other. I would say they're unlikely to be compatible soon. 

Closing as a duplicate of #441.

**Closed by zite** 2019-11-22 01:06 UTC
