### ISSUE TITLE
SteamVR with oculus quest 2 not working consistently

### ISSUE THREAD

**Issue by leozhang1** [ValveSoftware/steamvr_unity_plugin#1068] opened 2022-09-13 03:30 UTC
So when I add a player prefab (steamvr folder has a player prefab) into unity, I was able to hit play and see the world thru my headsets. But next time I open up this project, I get these errors.

![image](https://user-images.githubusercontent.com/43508492/189801282-7a6accd9-18b2-4fbe-86ef-2b63796920d0.png)

I didn't change a thing and yet it worked last time. I have everything configured (at least I hope so). Yet I still get these errors. I would appreciate anyone's effort to help.

**Comment by zite** [comment] 2023-02-08 20:45
Closing this issue for now as its been a few months and I'm not able to reproduce. If it is still a problem please provide a full editor log.

**Closed by zite** 2023-02-08 20:45 UTC
