### ISSUE TITLE
Windows Mixed Reality bindings

### ISSUE THREAD

**Issue by mikorigames** [ValveSoftware/steamvr_unity_plugin#360] opened 2019-03-15 08:22 UTC
I don't have a Windows Mixed Reality headset but how can i create a .json for it?

**Comment by timetosmile** [comment] 2019-03-18 07:55
I am also into this topic. 
I have a mixed reality Headset from Lenovo and when I opening the bindings ui from Unity I can assign all my actions and the most of them are working. But a few thins don't:

1. Where I can assign my skeletal to my controller? The Problem is that my hand poses are not working with the MR HMD. 

2. Is it possible to change the binding of the SteamVR button. Actual it is assigned to "Joystick Push". This is the worst place for this Function. Isn't it possible to override the Windows button on the controller? 
I can believe that this can get really annoying  because windows won't let you to do so. But it would be much better if could open steamVr from the Mixed reality UI or vice versa. I think you can unterstand what I mean. 

3. When I opening the controller bindings in VR then I see nothing. Just the panel at the bottom where choose between Steam, Desktop and Settings and also see my clock but nothing else. Not error display, not other feedback. Just nothing. 
By the way. I am using SteamVr beta 1.3.15. Mayhe this has something to do with it.

**Comment by pkarjala** [comment] 2019-03-22 20:50
1. I am also looking for this; it is possible Valve hasn't added them yet?

2. I don't think you can change the Windows button, as this is system bound outside of SteamVR.  However, I think they should re-bind the SteamVR home button to something like one of the menu buttons on the controller instead of the joystick click.

3.  I was just able to get this working in SteamVR 1.2.10, so it may be related?  I also had to restart SteamVR with no other controllers (such as an XBox controller) connect to the system.

**Comment by zite** [comment] 2019-03-29 00:05
Unfortunately Microsoft has not yet added Skeletal support to their SteamVR driver. So you won't be able to get skeletal input on those devices.

Windows Mixed Reality bindings should be included with the default set of JSONs allowing you to interact with the Interaction System Sample scene. You can change those bindings the same way you can change other bindings by hitting "Replace Default" at the bottom of the binding UI.

**Closed by zite** 2019-03-29 00:05 UTC

**Comment by timetosmile** [comment] 2019-04-03 07:52
Thank you, 

the binding setting is not a problem but how can I change the binding of the steamVR menu Button ?
