### ISSUE TITLE
Accessing pogo pin state for a tracker?

### ISSUE THREAD

**Issue by guiglass** [ValveSoftware/steamvr_unity_plugin#381] opened 2019-03-31 08:54 UTC
I am finding that using bindings is not working very well for trackers, and I need a way to access each of my tracker's pogo pins.

I see the device "/devices/htc/vive_trackerLHR-1ADEAAA3 -vive_tracker"

How can I access pogo pin values such as: "/input/trigger/click".

Please help, I am desperate to get trackers working properly!!!

**Comment by MahmoudAshraf-CIS** [comment] 2019-07-17 19:36
am facing the same problem, even downgrading to an older steam vr plugin version it didn't work

**Comment by nocanwin** [comment] 2020-01-29 17:18
see issue #152

**Comment by zite** [comment] 2021-06-28 17:02
Closing as a duplicate of #152

**Closed by zite** 2021-06-28 17:02 UTC
