### ISSUE TITLE
Flood of InvalidHandle errors for unbound optional actions in RC3

### ISSUE THREAD

**Issue by dantman** [ValveSoftware/steamvr_unity_plugin#110] opened 2018-09-02 23:21 UTC
I'm using the 2.0 RC3 plugin to setup SteamVR Input actions in an overlay.

The console is flooded with `GetDigitalActionData error ({fullPath}) InvalidHandle handle: {handle}` errors for every action that is not bound on the current controllers. Even when the action is marked as optional and not bound because there is no button that makes sense to bind it to.

![unityconsoleerror](https://user-images.githubusercontent.com/53399/44961799-d8946c80-aecb-11e8-9992-54b0dda4d754.png)

I have verified that buttons I do have bindings for don't show up in this error list, and that I can receive events from them.

**Comment by Mahdniss** [comment] 2018-09-13 00:41
I'm having a similar issue as I have indicated in my open issue #114 . I can't seem to find a root cause. However, I do have a binding for the only one I have created, and it is still throwing the InvalidHandle error. Perhaps it is not bound correctly. 

Would you mind sharing with me what you did after creating the input via the input manager?

**Comment by dantman** [comment] 2018-09-13 00:52
It probably won't be much of a reference. My setup is rather custom/messy because I'm writing an overlay in Unity instead of a game, and experimenting to see if I can hack the SteamVR Input system into working.
https://github.com/dantman/elite-vr-cockpit/compare/steamvr-input-actions

I did note this exclusively happens for actions that are defined but are not bound to a control. The code that gets the handle for an action string succeeds and each call returns a different handle (so the handle itself isn't invalid). And then the error happens when that handle is used in a certain function and there is no binding for that action.

**Comment by Mahdniss** [comment] 2018-09-14 02:46
Yes, and as it turns out my issue was a different bug altogether. I somehow messed up and placed my binding on a control it didn't support. So even though it showed up in the UI as assigned, it technically wasn't. Indirectly, this conversation was helpful as I dived into the function that creates the error message and went from there. Thanks!

**Comment by LucidDreamsVR** [comment] 2018-09-15 14:33
This also occurs if one or more of your controllers is not connected when you hit Play in the editor, which can happen often during development since the controllers go to sleep fairly quickly.

I was able to work around this issue by opening SteamVR Input from the Window menu, then removing and re-adding each of the actions that were producing errors. When you do this, just make sure you note the name, Type, and Required settings so you can recreate them as before. I am guessing you could alternatively switch away from using the "default" Action Set and use one of the others or create your own, but this will fix the default.

I'll look around in the code and see if I can submit a PR to fix this.

**Comment by LucidDreamsVR** [comment] 2018-09-15 15:40
Workaround if you are building the code yourself instead of using the unitypackage...simply change the error log on line 59 of SteamVR_Action_Boolean.cs to be a warning instead. I have not seen any negative side effects of doing this in my testing so far.
 
Debug.LogError("GetDigitalActionData error (" + fullPath + "): " + err.ToString() + " handle: " + handle.ToString());

becomes

Debug.LogWarning("GetDigitalActionData error (" + fullPath + "): " + err.ToString() + " handle: " + handle.ToString());

**Comment by LucidDreamsVR** [comment] 2018-09-15 16:11
If your controllers are turned off, then you will also need to repeat this pattern in the following locations:

SteamVR_Action_Single.cs line 49
SteamVR_Action_Pose.cs lines 87 & 128

BTW, not saying these are fixes for the issue, just workarounds to be able to continue running if you are trying to test other things and don't want to address this issue until later.

**Comment by bddckr** [comment] 2018-09-16 14:41
I believe this is fixed by a runtime update:
https://steamcommunity.com/app/250820

**Comment by zite** [comment] 2018-09-21 23:35
Thanks for the report and discussion everybody. This issue has been fixed in the recent SteamVR beta. We're strongly encouraging developers to switch to the beta for development purposes.

**Closed by zite** 2018-09-21 23:35 UTC
