### ISSUE TITLE
Cannot See Vive Controllers in VR with 1.2.3

### ISSUE THREAD

**Issue by davnkrit** [ValveSoftware/steamvr_unity_plugin#66] opened 2018-01-27 06:48 UTC
I have tried Unity versions 5.5.0f3, 5.5.3f1, 5.5.4p4, 5.6.1f1, and 2017.1.1f1 with version 1.2.3 of the SteamVR plugin and none will show the controllers.  All I'm doing is removing the Main Camera from an empty project, and dragging in the [CameraRig and [SteamVR] prefab into the scene and playing the scene.

The only version I can get working (see the controllers in VR) is 5.5.0f3 with a copy of SteamVR 1.2.0 plugin that I have from an old project.

Is there something different that has to be done for 1.2.3 to work?

**Comment by davnkrit** [comment] 2018-01-28 01:34
Looks like replacing the deprecated version of SteamVR_UpdateChars.cs with an old version of SteamVR_UpdateChars.cs (from 1.2.0) fixed it in Unity 5.6.1 (still had to add it as a component to [CameraRig]->Camera (head)->Camera(eye) ).

For 2017.3.0f3 I had to remove the if/end if section checking for UNITY_5_6, and NOT add the script as a component of the Camera (eye) to get it working.

Here's the 1.2.0 version of SteamVR_UpdateChars.cs in case someone needs it:

//======= Copyright (c) Valve Corporation, All rights reserved. ===============
//
// Purpose: Helper to update poses when using native OpenVR integration.
//
//=============================================================================

using UnityEngine;
using Valve.VR;

[ExecuteInEditMode]
public class SteamVR_UpdatePoses : MonoBehaviour
{
#if !(UNITY_5_6)
    void Awake()
    {
        var camera = GetComponent<Camera>();
        camera.stereoTargetEye = StereoTargetEyeMask.None;
        camera.clearFlags = CameraClearFlags.Nothing;
        camera.useOcclusionCulling = false;
        camera.cullingMask = 0;
        camera.depth = -9999;
    }
#endif
    void OnPreCull()
    {
        var compositor = OpenVR.Compositor;
        if (compositor != null)
        {
            var render = SteamVR_Render.instance;
            compositor.GetLastPoses(render.poses, render.gamePoses);
            SteamVR_Events.NewPoses.Send(render.poses);
            SteamVR_Events.NewPosesApplied.Send();
        }
    }
}

**Comment by gevarre** [comment] 2018-01-28 18:00
**Sorry for the cross-post, but here is the info I just added to issue #49 not knowing that this one had just been opened. They seem to be the same issue:**

I've talked to several vr devs in the Seattle area, and they seem to be having the same problem: If you leave things at their default, the models don't show up, if you manually override the model in unity (in the "Model Override" drop-down) to anything other than vr_controller_vive_1_5, the controllers show up and everything seems to work. I had just never noticed it before since I always make custom controller models.

These may or may not have anything to do with the actual problem, but here are the errors I'm now getting:

[Model] Render model does not support components, falling back to single mesh.
UnityEngine.Debug:Log(Object)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:285)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

Failed to load IVRRenderModels interface version IVRRenderModels_005
UnityEngine.Debug:LogError(Object)
RenderModelInterfaceHolder:get_instance() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:90)
SteamVR_RenderModel:LoadComponents(RenderModelInterfaceHolder, String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:507)
SteamVR_RenderModel:SetModel(String) (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:279)
SteamVR_RenderModel:Update() (at Assets/SteamVR/Scripts/SteamVR_RenderModel.cs:674)

**Comment by aleiby** [comment] 2018-01-30 22:03
Seem my comment in #49.  I am unable to reproduce this problem in 2017.1 or newer, however.

**Comment by gevarre** [comment] 2018-01-31 19:56
Weird. There's something going on though, and it may even be outside of Unity.

1. Fresh install of Unity 2017.
2. Started the SteamVR app first to be sure it was working fine.
3. Started 2017.3.0f3.
4. Downloaded the SteamVR plugin from the asset store.
5. Deleted the default camera.
6. Drug the [CameraRig] prefab into a scene.
7. Notice the absence of controllers, but no errors yet:
![controllerproblem1-2-3_01](https://user-images.githubusercontent.com/35581067/35637228-8b05dc74-06ab-11e8-9895-ad20518a307d.jpg)

8. Pressed play in the editor. Now I get errors:
![controllerproblem1-2-3_02](https://user-images.githubusercontent.com/35581067/35637267-a70298f4-06ab-11e8-8755-688b228bb0fb.jpg)

9. Exited play and overrode the default model of "none" with "vr_controller_05_wireless_b". Now the controllers show up:
![controllerproblem1-2-3_03](https://user-images.githubusercontent.com/35581067/35637348-d7d6859e-06ab-11e8-936d-d08ad9f18c5d.jpg)


More info: Perhaps this might not be related to the Unity plugin at all. I just noticed that if I bring up the steam overlay (by pressing the little button below the thumbpad), the controllers work, but they are invisible. If I play any game that uses the default controllers, like The Lab, they are likewise missing but working. However, if I bring up SteamVR Home, the controllers ARE there. Any apps that override the default controller with their own custom versions also work.

I even went so far as to uninstall SteamVR (through my Steam Library), make sure the rendermodels folder was gone, then reinstall SteamVR, but that didn't seem to make any difference. Is there somewhere else that SteamVR is referencing these models from?

Also note: I have confirmed from other devs I've talked to that this is also happening to them in 2017.

**Comment by gevarre** [comment] 2018-02-01 16:42
Thanks for the info. So here is the error, and sorry for the formatting. It's a long one:

Unable to load render model from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\
C:Program Files (x86)Steamsteamappsworkshopcontent250820675102547vr_controller_vive_1_5vr_controller_vive_1_5.obj\
C:Program Files (x86)Steamsteamappsworkshopcontent250820675102547vr_controller_vive_1_5vr_controller_vive_1_5.obj.obj: 

Cannot open file [C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\
C:Program Files (x86)Steamsteamappsworkshopcontent250820675102547vr_controller_vive_1_5vr_controller_vive_1_5.obj\
C:Program Files (x86)Steamsteamappsworkshopcontent250820675102547vr_controller_vive_1_5vr_controller_vive_1_5.obj.obj]

The above is actually all on one line. I have no idea how this works, but if you look at the paths that contain the folder "250820675102547", notice that there are no slashes in the path. Is this behaving correctly?

I did check the controller models in both places and they exist. When I import them into Maya, I get the following error:

Your OBJ file contains faces shared by multiple groups.
Maya cannot create multiple objects for this file.
A single mesh object will be created instead.
The OBJ group information will be captured in Maya sets.

I'm assuming this is innocuous and is just an artifact of the import, but I figured I'd better include it just in case. After opening in Maya, the file consists of 1 combined mesh of everything and some Maya groups that individually list every face and vertex. I haven't used OBJ in years, but again, I'm assuming this is normal.

Oh, and when I open vrclient_TheLab.txt, I see the exact same error with the same paths.

**Comment by aleiby** [comment] 2018-02-06 00:31
Looks like something is screwed up with the "modelskins" section of your steamvr.vrsettings file (under SteamInstallFolder/config.  Try deleting that section and trying again.

**Comment by gevarre** [comment] 2018-02-06 01:08
@aleiby: Yay! Deleting my config folder fixed the missing controllers. Thanks for the diagnostics. One last question though: In Unity, I'm still not seeing any controllers in the scene view, only in the game view when I hit play. I've never really paid attention to this because I've always used my own custom models before. Am I right in assuming that to see them in the scene view I have to use the Model Override and then switch it back to None before building? If so, it would be nice if they would default to a default model within Unity, but no biggie.

**Comment by aleiby** [comment] 2018-02-06 20:19
@gevarre Correct.

**Comment by gevarre** [comment] 2018-03-01 23:34
Update: I've been trying out 2018, and there now seems to be something else going on. I'm still trying to track down the exact cause and sequence of events, but when opening 2018, I now lose the controllers again with the same "Failed to load IVRRenderModels interface version IVRRenderModels_005".

Big difference this time is that there are no errors in the logs and the only way to get them back seems to be to COMPLETELY remove steamvr's config folder, uninstall steamvr completely from steam, restart the computer, reinstall everything, and run all the steamvr setup stuff again. Switching back to 2017 and then 2018 seems to cause the error again, though, as I said, I'm still trying to trace down exact repro steps.

**Comment by justinwasilenko** [comment] 2018-03-21 12:33
We have a problem where tracking works but the controller models don't show up in Standalone builds. The controller models show up in the editor though but once the project is built the controllers don't show up.

Using SteamVR 1.2.3, Unity 2017.3.1.p4.

**Comment by zite** [comment] 2018-09-21 23:56
I believe this issue has been fixed in recent versions of SteamVR and the Unity Plugin. Let me know if it's still an issue and I'll reopen.

**Closed by zite** 2018-09-21 23:56 UTC

**Comment by chengnay** [comment] 2019-09-04 03:40
@keithbradner Recently, developer complains that this issue still occurs in recent Unity and SteamVR version. Here is the link to the error log. https://github.com/ViveSoftware/ViveInputUtility-Unity/issues/136#issuecomment-527535072
