### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by AdamFrisby** [ValveSoftware/steamvr_unity_plugin#63] opened 2017-12-18 14:23 UTC
Hi there - 

Will this be updated soon to include MacOS support? (or is there a way to get it to work?)

Thanks!

**Comment by zite** [comment] 2018-10-02 23:30
Closing as a duplicate of a newer issue with more info

**Closed by zite** 2018-10-02 23:30 UTC

**Comment by AdamFrisby** [comment] 2018-10-03 02:03
I can't find the newer issue - do you have the issue#?
