### ISSUE TITLE
SteamVR Poser reacting with strange behavior; even with 2.3.2 update.

### ISSUE THREAD

**Issue by Wojtex28** [ValveSoftware/steamvr_unity_plugin#459] opened 2019-06-19 14:50 UTC
Hello, 
So, i have seen prevoius problems like this here:
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/427
https://github.com/ValveSoftware/steamvr_unity_plugin/issues/319

But for me this problem still occures with two hand interaction. I have visualised what happening here:
https://streamable.com/jyyaw

Basicly what is happening is that when i hold object with one hand, and then adding second one this poses getting those strange shapes (exact same issues as those linked above). This behavior happens only if i catch object with right hand first:
https://streamable.com/25y53 

Is there something that i doing wrong with my poses or that means that is SteamVR needs another fix?
Thanks for answer in advance.

**Comment by WaleedAmer** [comment] 2020-08-12 21:31
I'm having the same problem. It only happens with the left hand if I first grab with the right hand then add the left hand.

I'm guessing it has to do with the left hand's pose having negative values and canceling out with the positive values on the right hand, therefore setting all the bone values to zero for the left hand?

**Comment by zite** [comment] 2021-06-28 17:07
Closing as duplicate of #427

**Closed by zite** 2021-06-28 17:07 UTC
