### ISSUE TITLE
Editing current binding

### ISSUE THREAD

**Issue by chc2212** [ValveSoftware/steamvr_unity_plugin#151] opened 2018-10-09 07:57 UTC
When I click "Open binding UI", I can see some menu in chrome. 

But, when I click anything in that menu, the page doesn't show anything. 

There is no alternative way.. I tried it with chrome, incognito chrome, explorer, firefox.. Nothing works. I guess it is cookie problem.. 

I don't understand why you make us control these features through web which is unstable and has possibility to make problem like this.

**Comment by kisak-valve** [comment] 2018-10-09 11:48
Hello @chc2212, this is most likely a duplicate of #123. Closing in favor of the existing issue report.

**Closed by kisak-valve** 2018-10-09 11:48 UTC
