### ISSUE TITLE
SteamVR input generation stuck

### ISSUE THREAD

**Issue by BostonLeeK** [ValveSoftware/steamvr_unity_plugin#144] opened 2018-10-05 12:57 UTC
After importing the plugin get stuck on Generating scriptable objects and freeze unity.

**Comment by zite** [comment] 2018-10-05 17:31
Hey BostonLeeK, can you give me an editor log for when this happens to you? It should be in the following location C:\Users\%username%\AppData\Local\Unity\Editor\Editor.log

Does all of unity freeze? As in you can't click cancel?

**Comment by Frooxius** [comment] 2018-10-06 04:35
Hello. I've got the same issue, using an empty Unity project with Unity 2018.3.0b4. The whole Unity editor freezes, I can't even click cancel.

Here's my editor log file:
[Editor.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2452742/Editor.log)

In my existing project that I'm upgrading it gets stuck on earlier step "Generating action set classes...", but I can still click cancel, seems to be "NotSupportedException: Collection is of a fixed size" exception, log here:
[Editor.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2452751/Editor.log)

Not sure if the latter is some issue in my project or something I did while trying to get it to work, but I hope this helps.

**Comment by jcrapsey** [comment] 2018-10-08 00:55
I have been having this issue also, I dug around and found a call to EditorUtility.SetDirty(); (Line 294, 295 in SteamVR_Input_Generator.cs) was causing the lock up, and it seemed to only be locking up on prefabs that were in my opened scene. If you open an empty scene and tried generating again it seemed to work. This could be a bug with Unity not handling SetDirty on prefabs in the scene, I'm not sure I couldn't find any issues that fit that description.

I noticed that on a previous iteration of SteamVR input generation switched you to an open scene and switched you back to your opened scene, could this be a regression?

**Comment by zite** [comment] 2018-10-08 18:09
> Hello. I've got the same issue, using an empty Unity project with Unity 2018.3.0b4. The whole Unity editor freezes, I can't even click cancel.
> 
> Here's my editor log file:
> [Editor.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2452742/Editor.log)
> 
> In my existing project that I'm upgrading it gets stuck on earlier step "Generating action set classes...", but I can still click cancel, seems to be "NotSupportedException: Collection is of a fixed size" exception, log here:
> [Editor.log](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2452751/Editor.log)
> 
> Not sure if the latter is some issue in my project or something I did while trying to get it to work, but I hope this helps.

Thanks for the log, looks like you have a Take() extension that is causing issues in your CollectionsExtensions script:
  at CollectionsExtensions.Take[T] (System.Collections.Generic.IList`1[T] list, System.Int32 index) [0x00007] in D:\Sync\Projects\Software\Applications\NeoS\Neos Framework\BaseX\Source\Extensions\CollectionsExtensions.cs:47

**Comment by zite** [comment] 2018-10-08 18:36
Looks like 2018.3b4 is having issues with openvr in general. I'd recommend the earlier betas for now until we can resolve the issues with unity.

**Comment by zite** [comment] 2018-11-07 00:49
This should be fixed in the beta version of the plugin that I've released here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

Let me know if you're still having issues.

**Comment by KavanBahrami** [comment] 2018-11-12 23:13
Just came back after a month to see where input stands (#154 ) and am now having this issue with 18.3.b9

Is it worth using this beta release you've linked @keithbradner or should I just wait a bit longer for the next input system release? I don't want to keep tossing my work every fix.

**Comment by dpggit** [comment] 2019-01-10 03:02
i am using version 2.0.1, the last version in the Unity asset store and i have the SteamVR input generation stuck, it has been like an hour and not changing, tried twice but doesnt work, Cancel button works, it just has the message "Assigning default actions to monobehaviours"

**Comment by zite** [comment] 2019-01-16 00:08
I'd recommend the latest beta release. We've gone through a lot of serialization changes in the past couple months trying to accommodate both Unity 5.6 and nested prefabs in 2018.3, But I believe the version we'll release to the asset store should be compatible with the current beta.

**Comment by zite** [comment] 2019-01-31 01:14
Fixed in the latest release

**Closed by zite** 2019-01-31 01:14 UTC
Labels: Fixed in next release
