### ISSUE TITLE
What does OpenVR.Chaperone.GetPlayAreaRect() return after "Reset Standing Position"?

### ISSUE THREAD

**Issue by plmayer** [ValveSoftware/steamvr_unity_plugin#994] opened 2021-11-04 14:49 UTC
I'm using GetPlayAreaRect() to get the actual corner points of the playspace within the Chaperone. This works fine, i.e. they line up with the (rectangle within the) actual Chaperone - up to the point where the user selects "Reset Standing Position" in the SteamVR menu (which they can also do in the waiting room / SteamVR home / wherever, before a game even starts).

After that, GetPlayAreaRect() returns coordinates which I've not figured out how to use yet. They are different than before, and seem to define a space of the same size as before, with a center which seems to be rather arbitrary (not where the user was standing, that's for sure). They may or may not be within the Chaperone. What are these coordinates supposed to show?

What I'm after is to get is the "real" Chaperone positions, i.e. the rect positions of the wireframe mesh shown by the compositor, regardless of what the user resetted. Is that possible?

**Comment by kisak-valve** [comment] 2021-11-04 14:53
Hello @plmayer, please do not intentionally open duplicate issue reports. If you think that https://github.com/ValveSoftware/openvr/issues/1607 should be in this issue tracker, then let me know and I'll transfer it.

Closing as a duplicate of https://github.com/ValveSoftware/openvr/issues/1607.

**Closed by kisak-valve** 2021-11-04 14:53 UTC

**Comment by plmayer** [comment] 2021-11-04 14:59
Sorry, but to be frank, I wasn't sure where to put it, and where I can expect an answer. It seems like a bug to me, but I am not sure where. I *am* using the Unity plug-in, so if you think its better to discuss this here, then yes, please transfer it.
