### ISSUE TITLE
Actions dissapeared

### ISSUE THREAD

**Issue by dpggit** [ValveSoftware/steamvr_unity_plugin#375] opened 2019-03-23 16:31 UTC
I was playing my game and i realized that actions didnt work for no reason, i opened the ui bindings and i see one of the actions was missing dont know how, i added it again clicked Save and Generate in Unity 2018.2.17 and the latests steamvr version and gets stuck , i opened ui bindings again and everything is gone, there is not any action, now appears just this
![imagen](https://user-images.githubusercontent.com/10148361/54868871-8fd1d180-4d91-11e9-9694-1cb7c0c3c92d.png)
The previous system was MUCH better than this one, please change this system, has a lot of bugs, gets stuck generating and if not stuck takes ages to generate them, i think i will end using the Unity XR settings
EDIT : I have been trying to generate the actions several times and after many Unity crashes i got to get some actions back , i realized that i could add the actions in the UI bindings without needing to regenerate again

**Comment by zite** [comment] 2019-03-29 00:10
Generation should be nearly immediate. And unity should definitely not crash. What kind of action names do you have? Are you using version 2.2 of the plugin?

**Comment by lowbl-daniel** [comment] 2019-04-15 06:47
Hi, I seem to experience this problem sometimes too when i switch between multiple Unity Projects that make use of SteamVR input. I modified the "default" bindings for one of the other projects and I open it up in another project, the above unbound action happens for the default binding set. There will not be any errors or warnings, but the controller will not appear at all until the actions have been reassigned. There seems to be a few people who have reported missing controllers in the unity forums and it seems to be related to this issue as well.

I am currently using steamVR 2.2

**Comment by dpggit** [comment] 2019-05-24 17:48
After regenerating actions today dissapeared again, this system is a total disaster, steam 2.0 is much worse than previous versions

**Comment by zite** [comment] 2019-05-24 18:10
bindings and actions do not persist across projects.

What do you mean controllers will not appear until actions have been reassigned? Are you saving / replacing defaults in the binding UI?

Regenerating actions makes it so the binding ui and unity knows what actions you have. It should not have any effect on binding those actions to buttons other than exposing them to be bound.

**Comment by dpggit** [comment] 2019-05-24 18:14
It is the same project, i mean the actions i made dissapeared , for instance i had an action for touchpad persist and its gone,i just realized it was gone cause the game suddently stopped worked, it was after i updated to last steamvr version maybe has something to do with that, i will just try Unity input cause Steamvr system fails all the time

**Comment by zite** [comment] 2019-05-24 18:16
where does it disappear from? The actions list in the binding ui? The actions list in unity? Is your project possibly under version control and you're not committing the actions.json file?

**Comment by dpggit** [comment] 2019-05-24 18:19
Yes the actions in the binding ui webpage

**Comment by zite** [comment] 2019-05-27 22:00
I'm going to close this as well since you were having a variety of issues that it sounds like may have been causing this. If you or anybody else has reproducible steps for actions disappearing please create a new issue.

**Closed by zite** 2019-05-27 22:00 UTC
