### ISSUE TITLE
OPEN VR cant  install！！！！！！！！！！

### ISSUE THREAD

**Issue by 18210328369** [ValveSoftware/steamvr_unity_plugin#380] opened 2019-03-31 08:10 UTC
Package missing for Virtual Reality SDK OpenVR. Please add the OpenVR (Standalone) package using the Package Manager Window.
Will attempt to enable None instead.

is always this tip，but package manger don't cant find Openvr  sdk

**Comment by anuproy** [comment] 2019-04-09 18:40
I am also facing the same problem, I hope the editor will fix soon.

**Comment by zite** [comment] 2019-04-18 17:12
If there is no OpenVR listing in your package manager you probably are having firewall / proxy issues. Try this thread: https://forum.unity.com/threads/network-configuration.590470/

**Comment by kisak-valve** [comment] 2019-05-24 14:38
Closing pending feedback.

**Closed by kisak-valve** 2019-05-24 14:38 UTC
Labels: Need Retest

**Comment by JustinAtSama** [comment] 2019-05-24 17:12
Im not sure in the new update but, SteamVR2 does keep display a message that there is no OpenVR. The message displays when I open Unity, when I hit play in the editor.  I seriously had to comment out your line of code that forces this display. From my understanding, it is an unnecessary check since Unity claims to have OpenVR come with by default. I cant say for older versions of Unity, but this error message is display for version 2018.1.1f

**Comment by JustinAtSama** [comment] 2019-05-24 17:17
> If there is no OpenVR listing in your package manager you probably are having firewall / proxy issues. Try this thread: https://forum.unity.com/threads/network-configuration.590470/

I've tried this and it doesnt clean the error message. I added firewall exceptions and eventually turned off firewall. Unity's packagemanager does not have OpenVR listed nor does it say its installed. My advice is to provide a direct link to OpenVR package or sdk. I tried looking for it but such a thing doesnt seem to exist.

**Comment by kisak-valve** [comment] 2019-05-24 17:25
Hello @JustinAtSama, looks like #310 and #393 have the same symptoms as this issue report and we didn't hear back from @keithbradner's request to retest here. I don't see value in re-opening this issue report based on your comments when the issue is being tracked elsewhere as well.

Feel free to add your findings to one of the other issue reports so it doesn't get buried.
