### ISSUE TITLE
SteamVR_Action_In.GetDeviceComponentName(inputSource) returns a binary string

### ISSUE THREAD

**Issue by vatbub** [ValveSoftware/steamvr_unity_plugin#167] opened 2018-10-22 10:51 UTC
`SteamVR_Action_In.GetDeviceComponentName(inputSource)` returns a string that looks much like this:

```
115991141111081089511910410110110800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

When looking into the source code of that method, one can see that it calls `lastInputOriginInfo[inputSource].rchRenderModelComponentName` which in turn assembles the component name. `rchRenderModelComponentName` does that by putting all bytes that represent the component name into a `StringBuilder`. The issue lies in the fact that adding a byte to a `StringBuilder` through `StringBuilder.append(byte)` results in a call to `byte.ToString()` which converts the byte into its string representation (e. g. `"115"`). The above code should instead be:

```C#
public string rchRenderModelComponentName
	{
		get
		{
			var stringBuilder = new System.Text.StringBuilder(128);
			stringBuilder.Append(System.Text.Encoding.UTF8.GetString(new[] {rchRenderModelComponentName0}));
			stringBuilder.Append(System.Text.Encoding.UTF8.GetString(new[] {rchRenderModelComponentName1}));
			// ...
			return stringBuilder.ToString();
		}
	}
```

---
System configuration:
Unity v5.5.4f1 Personal
SteamVR v2.0.1

**Comment by zite** [comment] 2018-10-22 17:58
Yeah sorry, that was a regression. We've got a fix for that which will go into the next update. For now you can replace that function with this:

`
return new string(new char[] {
				(char)rchRenderModelComponentName0,
				(char)rchRenderModelComponentName1,
				(char)rchRenderModelComponentName2,
				(char)rchRenderModelComponentName3,
				(char)rchRenderModelComponentName4,
				(char)rchRenderModelComponentName5,
				(char)rchRenderModelComponentName6,
				(char)rchRenderModelComponentName7,
				(char)rchRenderModelComponentName8,
				(char)rchRenderModelComponentName9,
				(char)rchRenderModelComponentName10,
				(char)rchRenderModelComponentName11,
				(char)rchRenderModelComponentName12,
				(char)rchRenderModelComponentName13,
				(char)rchRenderModelComponentName14,
				(char)rchRenderModelComponentName15,
				(char)rchRenderModelComponentName16,
				(char)rchRenderModelComponentName17,
				(char)rchRenderModelComponentName18,
				(char)rchRenderModelComponentName19,
				(char)rchRenderModelComponentName20,
				(char)rchRenderModelComponentName21,
				(char)rchRenderModelComponentName22,
				(char)rchRenderModelComponentName23,
				(char)rchRenderModelComponentName24,
				(char)rchRenderModelComponentName25,
				(char)rchRenderModelComponentName26,
				(char)rchRenderModelComponentName27,
				(char)rchRenderModelComponentName28,
				(char)rchRenderModelComponentName29,
				(char)rchRenderModelComponentName30,
				(char)rchRenderModelComponentName31,
				(char)rchRenderModelComponentName32,
				(char)rchRenderModelComponentName33,
				(char)rchRenderModelComponentName34,
				(char)rchRenderModelComponentName35,
				(char)rchRenderModelComponentName36,
				(char)rchRenderModelComponentName37,
				(char)rchRenderModelComponentName38,
				(char)rchRenderModelComponentName39,
				(char)rchRenderModelComponentName40,
				(char)rchRenderModelComponentName41,
				(char)rchRenderModelComponentName42,
				(char)rchRenderModelComponentName43,
				(char)rchRenderModelComponentName44,
				(char)rchRenderModelComponentName45,
				(char)rchRenderModelComponentName46,
				(char)rchRenderModelComponentName47,
				(char)rchRenderModelComponentName48,
				(char)rchRenderModelComponentName49,
				(char)rchRenderModelComponentName50,
				(char)rchRenderModelComponentName51,
				(char)rchRenderModelComponentName52,
				(char)rchRenderModelComponentName53,
				(char)rchRenderModelComponentName54,
				(char)rchRenderModelComponentName55,
				(char)rchRenderModelComponentName56,
				(char)rchRenderModelComponentName57,
				(char)rchRenderModelComponentName58,
				(char)rchRenderModelComponentName59,
				(char)rchRenderModelComponentName60,
				(char)rchRenderModelComponentName61,
				(char)rchRenderModelComponentName62,
				(char)rchRenderModelComponentName63,
				(char)rchRenderModelComponentName64,
				(char)rchRenderModelComponentName65,
				(char)rchRenderModelComponentName66,
				(char)rchRenderModelComponentName67,
				(char)rchRenderModelComponentName68,
				(char)rchRenderModelComponentName69,
				(char)rchRenderModelComponentName70,
				(char)rchRenderModelComponentName71,
				(char)rchRenderModelComponentName72,
				(char)rchRenderModelComponentName73,
				(char)rchRenderModelComponentName74,
				(char)rchRenderModelComponentName75,
				(char)rchRenderModelComponentName76,
				(char)rchRenderModelComponentName77,
				(char)rchRenderModelComponentName78,
				(char)rchRenderModelComponentName79,
				(char)rchRenderModelComponentName80,
				(char)rchRenderModelComponentName81,
				(char)rchRenderModelComponentName82,
				(char)rchRenderModelComponentName83,
				(char)rchRenderModelComponentName84,
				(char)rchRenderModelComponentName85,
				(char)rchRenderModelComponentName86,
				(char)rchRenderModelComponentName87,
				(char)rchRenderModelComponentName88,
				(char)rchRenderModelComponentName89,
				(char)rchRenderModelComponentName90,
				(char)rchRenderModelComponentName91,
				(char)rchRenderModelComponentName92,
				(char)rchRenderModelComponentName93,
				(char)rchRenderModelComponentName94,
				(char)rchRenderModelComponentName95,
				(char)rchRenderModelComponentName96,
				(char)rchRenderModelComponentName97,
				(char)rchRenderModelComponentName98,
				(char)rchRenderModelComponentName99,
				(char)rchRenderModelComponentName100,
				(char)rchRenderModelComponentName101,
				(char)rchRenderModelComponentName102,
				(char)rchRenderModelComponentName103,
				(char)rchRenderModelComponentName104,
				(char)rchRenderModelComponentName105,
				(char)rchRenderModelComponentName106,
				(char)rchRenderModelComponentName107,
				(char)rchRenderModelComponentName108,
				(char)rchRenderModelComponentName109,
				(char)rchRenderModelComponentName110,
				(char)rchRenderModelComponentName111,
				(char)rchRenderModelComponentName112,
				(char)rchRenderModelComponentName113,
				(char)rchRenderModelComponentName114,
				(char)rchRenderModelComponentName115,
				(char)rchRenderModelComponentName116,
				(char)rchRenderModelComponentName117,
				(char)rchRenderModelComponentName118,
				(char)rchRenderModelComponentName119,
				(char)rchRenderModelComponentName120,
				(char)rchRenderModelComponentName121,
				(char)rchRenderModelComponentName122,
				(char)rchRenderModelComponentName123,
				(char)rchRenderModelComponentName124,
				(char)rchRenderModelComponentName125,
				(char)rchRenderModelComponentName126,
				(char)rchRenderModelComponentName127
			}).TrimEnd('\0');
`

**Comment by AndersMalmgren** [comment] 2018-10-28 19:46
I updated with the code (You probably want to cache that, looks like it will allocate). 
I tried it on a action bound to Touchpad on a Vive controller and got **scroll_wheel**. Seems wring :D

**Comment by zite** [comment] 2018-11-07 00:39
FYI this function not returning a string should be fixed on the beta version of the plugin up at https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1b2

It not always returning the right button however is still a work in progress.

**Closed** 2019-01-02 18:17 UTC
